### ISSUE TITLE
add new items to TODO

### ISSUE THREAD

**Issue by rexim** [tsoding/todo-rs#2]

**Comment by koutoftimer** [comment]
Taken

**Comment by rexim** [comment]
@koutoftimer nope

![2021-06-24-225152_600x279_scrot](https://user-images.githubusercontent.com/165283/123294448-0d6f8380-d53f-11eb-8534-8e0b5705f031.png)

**Comment by koutoftimer** [comment]
@rexim just bunch of ideas

Introduce modes like in vim

```rust
enum Mode {
    Normal,
    Insert,
}
```

Then handle user's input depending on mode
```rust
let key = getch();
match mode {
    Mode::Normal =>  match key as u8 as char { ... },
    Mode::Insert => match key as u8 as char { ... },
}
```

Notification string should show what mode we are currently in 
```rust
let info_bar = format!("[{}] {}", mode, notification);
```
